#!/bin/bash

./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1perl4c.Nehalem/xeon-4-1_1perl4c.Nehalem.stats > ~/DRAMSim2/results/perl_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1bzip4c.Nehalem/xeon-4-1_1bzip4c.Nehalem.stats > ~/DRAMSim2/results/bzip_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1gcc4c.Nehalem/xeon-4-1_1gcc4c.Nehalem.stats > ~/DRAMSim2/results/gcc_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1mcf4c.Nehalem/xeon-4-1_1mcf4c.Nehalem.stats > ~/DRAMSim2/results/mcf_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1gobmk4c.Nehalem/xeon-4-1_1gobmk4c.Nehalem.stats > ~/DRAMSim2/results/gobmk_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1hmmer4c.Nehalem/xeon-4-1_1hmmer4c.Nehalem.stats > ~/DRAMSim2/results/hmmer_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1sjeng4c.Nehalem/xeon-4-1_1sjeng4c.Nehalem.stats > ~/DRAMSim2/results/sjeng_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1quantum4c.Nehalem/xeon-4-1_1quantum4c.Nehalem.stats > ~/DRAMSim2/results/quantum_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1h2644c.Nehalem/xeon-4-1_1h2644c.Nehalem.stats > ~/DRAMSim2/results/h264ref_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1omnetpp4c.Nehalem/xeon-4-1_1omnetpp4c.Nehalem.stats > ~/DRAMSim2/results/omnetpp_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1astar4c.Nehalem/xeon-4-1_1astar4c.Nehalem.stats > ~/DRAMSim2/results/astar_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1xalanc4c.Nehalem/xeon-4-1_1xalanc4c.Nehalem.stats > ~/DRAMSim2/results/xalanc_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1bwaves4c.Nehalem/xeon-4-1_1bwaves4c.Nehalem.stats > ~/DRAMSim2/results/bwaves_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1gamess4c.Nehalem/xeon-4-1_1gamess4c.Nehalem.stats > ~/DRAMSim2/results/gamess_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1zeusmp4c.Nehalem/xeon-4-1_1zeusmp4c.Nehalem.stats > ~/DRAMSim2/results/zeusmp_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1gromacs4c.Nehalem/xeon-4-1_1gromacs4c.Nehalem.stats > ~/DRAMSim2/results/gromacs_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1cactusADM4c.Nehalem/xeon-4-1_1cactusADM4c.Nehalem.stats > ~/DRAMSim2/results/cactusADM_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1leslie3d4c.Nehalem/xeon-4-1_1leslie3d4c.Nehalem.stats > ~/DRAMSim2/results/leslie_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1namd4c.Nehalem/xeon-4-1_1namd4c.Nehalem.stats > ~/DRAMSim2/results/namd_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1deal4c.Nehalem/xeon-4-1_1deal4c.Nehalem.stats > ~/DRAMSim2/results/deal_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1soplex4c.Nehalem/xeon-4-1_1soplex4c.Nehalem.stats > ~/DRAMSim2/results/soplex_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1povray4c.Nehalem/xeon-4-1_1povray4c.Nehalem.stats > ~/DRAMSim2/results/povray_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1calculix4c.Nehalem/xeon-4-1_1calculix4c.Nehalem.stats > ~/DRAMSim2/results/calculix_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1gems4c.Nehalem/xeon-4-1_1gems4c.Nehalem.stats > ~/DRAMSim2/results/gems_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1tonto4c.Nehalem/xeon-4-1_1tonto4c.Nehalem.stats > ~/DRAMSim2/results/tonto_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1lbm4c.Nehalem/xeon-4-1_1lbm4c.Nehalem.stats > ~/DRAMSim2/results/lbm_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1wrf4c.Nehalem/xeon-4-1_1wrf4c.Nehalem.stats > ~/DRAMSim2/results/wrf_cache_summary.txt
./mstats.py -y --yaml-out -t total --cache-summary ~/DRAMSim2/results/spec2006/xeon-4-1_1sphinx4c.Nehalem/xeon-4-1_1sphinx4c.Nehalem.stats > ~/DRAMSim2/results/sphinx_cache_summary.txt
